import type {
  CompanyEvent,
  EventActivity,
  EventGalleryPhoto,
} from "$lib/types/events";

export const upcomingEvent: CompanyEvent = {
  id: "team-football-evening",
  title: "Studio League & Outdoor Match",
  summary:
    "An energized inter-department tournament bringing our post-production, 3D, and production crews together under the lights.",
  date: "August 24, 2026",
  location: "Dhaka Sports Arena",
  status: "upcoming",
  format: "Sports League",
  image: "/images/events/football-match/studio-click-house-football-match-01.jpg",
  imageAlt: "Studio Click House team members during evening football match",
  focus: ["Team synergy", "Friendly rivalry", "Outdoor recharge"],
};

export const eventGalleryPhotos: EventGalleryPhoto[] = [
  // --- Nepal Tour (18 Unique Photos) ---
  {
    id: "nepal-tour-01",
    src: "/images/events/nepal-tour/studio-click-house-nepal-tour-08.webp",
    alt: "Studio Click House team holding official tour banner at Nepal suspension bridge",
    category: "nepal-tour",
    categoryLabel: "Nepal Tour",
    caption: "Official studio expedition banner at the Himalayan suspension bridge",
  },
  {
    id: "nepal-tour-02",
    src: "/images/events/nepal-tour/studio-click-house-nepal-tour-05.webp",
    alt: "Studio Click House team in matching polo shirts with luggage outside Hotel Thamel",
    category: "nepal-tour",
    categoryLabel: "Nepal Tour",
    caption: "Arrival at Hotel Thamel in Kathmandu with the team",
  },
  {
    id: "nepal-tour-03",
    src: "/images/events/nepal-tour/studio-click-house-nepal-tour-06.webp",
    alt: "Studio Click House colleagues walking along mountain pine trail with Bangladesh flag",
    category: "nepal-tour",
    categoryLabel: "Nepal Tour",
    caption: "Ascending scenic pine trails adorned with prayer flags",
  },
  {
    id: "nepal-tour-04",
    src: "/images/events/nepal-tour/studio-click-house-nepal-tour-01.webp",
    alt: "Studio Click House team members displaying passports and boarding passes at airport",
    category: "nepal-tour",
    categoryLabel: "Nepal Tour",
    caption: "Boarding call: departing for Kathmandu, Nepal",
  },
  {
    id: "nepal-tour-05",
    src: "/images/events/nepal-tour/studio-click-house-nepal-tour-10.webp",
    alt: "Studio Click House team with expedition banner by mountain waterfall",
    category: "nepal-tour",
    categoryLabel: "Nepal Tour",
    caption: "Team gathering by a roaring mountain cascade",
  },
  {
    id: "nepal-tour-06",
    src: "/images/events/nepal-tour/studio-click-house-nepal-tour-17.webp",
    alt: "Studio Click House team sitting together along the high suspension bridge",
    category: "nepal-tour",
    categoryLabel: "Nepal Tour",
    caption: "Resting mid-span above the lush Himalayan gorge",
  },
  {
    id: "nepal-tour-07",
    src: "/images/events/nepal-tour/studio-click-house-nepal-tour-11.webp",
    alt: "Studio Click House creative crew group portrait on mountain ridge",
    category: "nepal-tour",
    categoryLabel: "Nepal Tour",
    caption: "Full studio collective atop the verdant ridgeline",
  },
  {
    id: "nepal-tour-08",
    src: "/images/events/nepal-tour/studio-click-house-nepal-tour-18.webp",
    alt: "Panoramic view of suspension bridge spanning across mountain valley",
    category: "nepal-tour",
    categoryLabel: "Nepal Tour",
    caption: "Dramatically suspended across the deep pine valley",
  },
  {
    id: "nepal-tour-09",
    src: "/images/events/nepal-tour/studio-click-house-nepal-tour-03.webp",
    alt: "Studio Click House team posing at historic plaza with Nepal flags",
    category: "nepal-tour",
    categoryLabel: "Nepal Tour",
    caption: "City landmarks and heritage plazas in Nepal",
  },
  {
    id: "nepal-tour-10",
    src: "/images/events/nepal-tour/studio-click-house-nepal-tour-16.webp",
    alt: "Studio Click House colleagues rooftop terrace selfie against Kathmandu cityscape",
    category: "nepal-tour",
    categoryLabel: "Nepal Tour",
    caption: "Rooftop evening breeze overlooking Kathmandu",
  },
  {
    id: "nepal-tour-11",
    src: "/images/events/nepal-tour/studio-click-house-nepal-tour-07.webp",
    alt: "Studio Click House team proudly holding tour banner at bridge crossing",
    category: "nepal-tour",
    categoryLabel: "Nepal Tour",
    caption: "Commemorating our 1st International Tour milestone",
  },
  {
    id: "nepal-tour-12",
    src: "/images/events/nepal-tour/studio-click-house-nepal-tour-12.webp",
    alt: "Team member waving Bangladesh flag against clear Himalayan skies",
    category: "nepal-tour",
    categoryLabel: "Nepal Tour",
    caption: "Waving our national colors high in the mountains",
  },
  {
    id: "nepal-tour-13",
    src: "/images/events/nepal-tour/studio-click-house-nepal-tour-04.webp",
    alt: "Vertical view of team gathered at Kathmandu flag square",
    category: "nepal-tour",
    categoryLabel: "Nepal Tour",
    caption: "Vibrant city moments in the Kathmandu valley",
  },
  {
    id: "nepal-tour-14",
    src: "/images/events/nepal-tour/studio-click-house-nepal-tour-13.webp",
    alt: "Colleague holding national flag amidst tall Himalayan pines",
    category: "nepal-tour",
    categoryLabel: "Nepal Tour",
    caption: "Pride and friendship among towering pines",
  },
  {
    id: "nepal-tour-15",
    src: "/images/events/nepal-tour/studio-click-house-nepal-tour-14.webp",
    alt: "Team member along pine forest trail during mountain excursion",
    category: "nepal-tour",
    categoryLabel: "Nepal Tour",
    caption: "Quiet nature walk through the mountain forest",
  },
  {
    id: "nepal-tour-16",
    src: "/images/events/nepal-tour/studio-click-house-nepal-tour-15.webp",
    alt: "Sunlight filtering through tall pine forest in Nepal",
    category: "nepal-tour",
    categoryLabel: "Nepal Tour",
    caption: "Golden mountain light through the pine trees",
  },
  {
    id: "nepal-tour-17",
    src: "/images/events/nepal-tour/studio-click-house-nepal-tour-19.webp",
    alt: "Team member seated peacefully along the suspension bridge walkway",
    category: "nepal-tour",
    categoryLabel: "Nepal Tour",
    caption: "Quiet contemplation over the mountain gorge",
  },
  {
    id: "nepal-tour-18",
    src: "/images/events/nepal-tour/studio-click-house-nepal-tour-09.webp",
    alt: "Wide shot of team and travelers along the mountain bridge",
    category: "nepal-tour",
    categoryLabel: "Nepal Tour",
    caption: "The bridge connecting trails and memories",
  },

  // --- Mawa Evening Tour (10 Photos) ---
  {
    id: "mawa-evening-01",
    src: "/images/events/mawa-evening/studio-click-house-mawa-evening-01.jpg",
    alt: "Studio Click House team sunset road trip to Mawa Padma River",
    category: "mawa-evening",
    categoryLabel: "Mawa Evening",
    caption: "Setting out for sunset by the Padma riverbank",
  },
  {
    id: "mawa-evening-02",
    src: "/images/events/mawa-evening/studio-click-house-mawa-evening-02.jpg",
    alt: "Studio Click House members enjoying river breeze along Mawa Ghat",
    category: "mawa-evening",
    categoryLabel: "Mawa Evening",
    caption: "River breeze and expansive open skies",
  },
  {
    id: "mawa-evening-03",
    src: "/images/events/mawa-evening/studio-click-house-mawa-evening-03.jpg",
    alt: "Studio Click House crew gathered at traditional Mawa fish feast",
    category: "mawa-evening",
    categoryLabel: "Mawa Evening",
    caption: "The famous Padma Ilish dinner with the whole crew",
  },
  {
    id: "mawa-evening-04",
    src: "/images/events/mawa-evening/studio-click-house-mawa-evening-04.jpg",
    alt: "Studio Click House colleagues laughing by the riverside at Mawa",
    category: "mawa-evening",
    categoryLabel: "Mawa Evening",
    caption: "Candid roadside stories and team cheer",
  },
  {
    id: "mawa-evening-05",
    src: "/images/events/mawa-evening/studio-click-house-mawa-evening-05.jpg",
    alt: "Studio Click House team members posing on the Padma bridge access road",
    category: "mawa-evening",
    categoryLabel: "Mawa Evening",
    caption: "Sunset silhouettes along the modern expressway",
  },
  {
    id: "mawa-evening-06",
    src: "/images/events/mawa-evening/studio-click-house-mawa-evening-06.jpg",
    alt: "Studio Click House team group photo overlooking the river at dusk",
    category: "mawa-evening",
    categoryLabel: "Mawa Evening",
    caption: "Twilight colors over the waters of Bengal",
  },
  {
    id: "mawa-evening-07",
    src: "/images/events/mawa-evening/studio-click-house-mawa-evening-07.jpg",
    alt: "Studio Click House members sharing tea under evening lanterns in Mawa",
    category: "mawa-evening",
    categoryLabel: "Mawa Evening",
    caption: "Night air, hot tea, and lively conversation",
  },
  {
    id: "mawa-evening-08",
    src: "/images/events/mawa-evening/studio-click-house-mawa-evening-08.jpg",
    alt: "Studio Click House team portrait at Mawa riverside restaurant",
    category: "mawa-evening",
    categoryLabel: "Mawa Evening",
    caption: "Surrounded by good food and great people",
  },
  {
    id: "mawa-evening-09",
    src: "/images/events/mawa-evening/studio-click-house-mawa-evening-09.jpg",
    alt: "Studio Click House colleagues celebrating memorable evening in Mawa",
    category: "mawa-evening",
    categoryLabel: "Mawa Evening",
    caption: "Unwinding after long creative production cycles",
  },
  {
    id: "mawa-evening-10",
    src: "/images/events/mawa-evening/studio-click-house-mawa-evening-10.jpg",
    alt: "Studio Click House team departure under night lights on the expressway",
    category: "mawa-evening",
    categoryLabel: "Mawa Evening",
    caption: "Heading home with full hearts and fresh energy",
  },

  // --- Football Match (16 Photos) ---
  {
    id: "football-match-01",
    src: "/images/events/football-match/studio-click-house-football-match-01.jpg",
    alt: "Studio Click House team football squad assembled on the turf",
    category: "football-match",
    categoryLabel: "Football Match",
    caption: "The teams assembled under stadium lights",
  },
  {
    id: "football-match-02",
    src: "/images/events/football-match/studio-click-house-football-match-02.jpg",
    alt: "Studio Click House football match action shot on the pitch",
    category: "football-match",
    categoryLabel: "Football Match",
    caption: "Kickoff: rapid passing and high-energy pressing",
  },
  {
    id: "football-match-03",
    src: "/images/events/football-match/studio-click-house-football-match-03.jpg",
    alt: "Studio Click House players competing for the ball during match",
    category: "football-match",
    categoryLabel: "Football Match",
    caption: "Fierce competition and athletic skill",
  },
  {
    id: "football-match-04",
    src: "/images/events/football-match/studio-click-house-football-match-04.jpg",
    alt: "Studio Click House teammates celebrating a goal on the turf",
    category: "football-match",
    categoryLabel: "Football Match",
    caption: "Celebrating a decisive strike into top corner",
  },
  {
    id: "football-match-05",
    src: "/images/events/football-match/studio-click-house-football-match-05.jpg",
    alt: "Studio Click House team goalkeeper in focus during evening match",
    category: "football-match",
    categoryLabel: "Football Match",
    caption: "Sharp reflexes between the goalposts",
  },
  {
    id: "football-match-06",
    src: "/images/events/football-match/studio-click-house-football-match-06.jpg",
    alt: "Studio Click House colleagues cheering passionately from the sidelines",
    category: "football-match",
    categoryLabel: "Football Match",
    caption: "The sideline support section bringing the noise",
  },
  {
    id: "football-match-07",
    src: "/images/events/football-match/studio-click-house-football-match-07.jpg",
    alt: "Studio Click House team halftime strategy huddle on the pitch",
    category: "football-match",
    categoryLabel: "Football Match",
    caption: "Tactical halftime discussions and water break",
  },
  {
    id: "football-match-08",
    src: "/images/events/football-match/studio-click-house-football-match-08.jpg",
    alt: "Studio Click House players running drills and counter-attacks",
    category: "football-match",
    categoryLabel: "Football Match",
    caption: "Fast breaks on the counter",
  },
  {
    id: "football-match-09",
    src: "/images/events/football-match/studio-click-house-football-match-09.jpg",
    alt: "Studio Click House team captains shaking hands with smiles",
    category: "football-match",
    categoryLabel: "Football Match",
    caption: "Mutual respect and true sporting spirit",
  },
  {
    id: "football-match-10",
    src: "/images/events/football-match/studio-click-house-football-match-10.jpg",
    alt: "Studio Click House striker shooting on goal during tournament",
    category: "football-match",
    categoryLabel: "Football Match",
    caption: "Precision shooting under pressure",
  },
  {
    id: "football-match-11",
    src: "/images/events/football-match/studio-click-house-football-match-11.jpg",
    alt: "Studio Click House squad resting on the bench with water bottles",
    category: "football-match",
    categoryLabel: "Football Match",
    caption: "Hydration, big smiles, and banter",
  },
  {
    id: "football-match-12",
    src: "/images/events/football-match/studio-click-house-football-match-12.jpg",
    alt: "Studio Click House defensive tackle on the artificial turf",
    category: "football-match",
    categoryLabel: "Football Match",
    caption: "Solid defensive teamwork",
  },
  {
    id: "football-match-13",
    src: "/images/events/football-match/studio-click-house-football-match-13.jpg",
    alt: "Studio Click House match final whistle hugs and celebrations",
    category: "football-match",
    categoryLabel: "Football Match",
    caption: "Full-time whistle: embracing after a great battle",
  },
  {
    id: "football-match-14",
    src: "/images/events/football-match/studio-click-house-football-match-14.jpg",
    alt: "Studio Click House tournament winners posing with medals",
    category: "football-match",
    categoryLabel: "Football Match",
    caption: "Champions lifting their tournament medals",
  },
  {
    id: "football-match-15",
    src: "/images/events/football-match/studio-click-house-football-match-15.jpg",
    alt: "Studio Click House players enjoying post-match meal together",
    category: "football-match",
    categoryLabel: "Football Match",
    caption: "Post-game dinner to recap the match highlights",
  },
  {
    id: "football-match-16",
    src: "/images/events/football-match/studio-click-house-football-match-16.jpg",
    alt: "Studio Click House complete tournament group portrait on turf",
    category: "football-match",
    categoryLabel: "Football Match",
    caption: "One united studio across all departments",
  },

  // --- Cox's Bazar (6 Photos) ---
  {
    id: "coxs-bazar-01",
    src: "/images/events/coxs-bazar/studio-click-house-coxs-bazar-01.jpg",
    alt: "Studio Click House team enjoying seaside breeze at Cox's Bazar beach",
    category: "coxs-bazar",
    categoryLabel: "Cox's Bazar",
    caption: "Seaside waves and coastal freedom",
  },
  {
    id: "coxs-bazar-02",
    src: "/images/events/coxs-bazar/studio-click-house-coxs-bazar-02.jpg",
    alt: "Studio Click House creative team group photo along the shoreline",
    category: "coxs-bazar",
    categoryLabel: "Cox's Bazar",
    caption: "Team assembly at the world's longest natural beach",
  },
  {
    id: "coxs-bazar-03",
    src: "/images/events/coxs-bazar/studio-click-house-coxs-bazar-03.jpg",
    alt: "Studio Click House colleagues walking barefoot on Cox's Bazar sand",
    category: "coxs-bazar",
    categoryLabel: "Cox's Bazar",
    caption: "Barefoot beach walks at golden hour",
  },
  {
    id: "coxs-bazar-04",
    src: "/images/events/coxs-bazar/studio-click-house-coxs-bazar-04.jpg",
    alt: "Studio Click House team members smiling and enjoying coastal sunshine",
    category: "coxs-bazar",
    categoryLabel: "Cox's Bazar",
    caption: "Coastal sunshine and positive vibes",
  },
  {
    id: "coxs-bazar-05",
    src: "/images/events/coxs-bazar/studio-click-house-coxs-bazar-05.jpg",
    alt: "Studio Click House evening gathering near Cox's Bazar beach resort",
    category: "coxs-bazar",
    categoryLabel: "Cox's Bazar",
    caption: "Relaxing resort evening by the ocean",
  },
  {
    id: "coxs-bazar-06",
    src: "/images/events/coxs-bazar/studio-click-house-coxs-bazar-06.jpg",
    alt: "Studio Click House team watching sunset over the Bay of Bengal",
    category: "coxs-bazar",
    categoryLabel: "Cox's Bazar",
    caption: "Sunset over the Bay of Bengal",
  },

  // --- Dinner Buffet (9 Photos) ---
  {
    id: "dinner-buffet-01",
    src: "/images/events/dinner-buffet/studio-click-house-dinner-buffet-01.jpg",
    alt: "Studio Click House annual dinner buffet banquet room and team members",
    category: "dinner-buffet",
    categoryLabel: "Dinner Buffet",
    caption: "Annual gala dinner welcoming the studio team",
  },
  {
    id: "dinner-buffet-02",
    src: "/images/events/dinner-buffet/studio-click-house-dinner-buffet-02.jpg",
    alt: "Studio Click House colleagues enjoying festive banquet dinner together",
    category: "dinner-buffet",
    categoryLabel: "Dinner Buffet",
    caption: "Delicious dining and warm companionship",
  },
  {
    id: "dinner-buffet-03",
    src: "/images/events/dinner-buffet/studio-click-house-dinner-buffet-03.jpg",
    alt: "Studio Click House team members sharing stories at the dinner table",
    category: "dinner-buffet",
    categoryLabel: "Dinner Buffet",
    caption: "Good conversation and genuine smiles",
  },
  {
    id: "dinner-buffet-04",
    src: "/images/events/dinner-buffet/studio-click-house-dinner-buffet-04.jpg",
    alt: "Studio Click House team group toast at annual celebratory dinner",
    category: "dinner-buffet",
    categoryLabel: "Dinner Buffet",
    caption: "Raising a toast to creative milestones",
  },
  {
    id: "dinner-buffet-05",
    src: "/images/events/dinner-buffet/studio-click-house-dinner-buffet-05.jpg",
    alt: "Studio Click House colleagues posing during annual buffet celebration",
    category: "dinner-buffet",
    categoryLabel: "Dinner Buffet",
    caption: "Dressed up for a memorable studio evening",
  },
  {
    id: "dinner-buffet-06",
    src: "/images/events/dinner-buffet/studio-click-house-dinner-buffet-06.jpg",
    alt: "Studio Click House team members laughing together at the buffet hall",
    category: "dinner-buffet",
    categoryLabel: "Dinner Buffet",
    caption: "Laughter that defines our studio culture",
  },
  {
    id: "dinner-buffet-07",
    src: "/images/events/dinner-buffet/studio-click-house-dinner-buffet-07.jpg",
    alt: "Studio Click House team enjoying gourmet buffet selections",
    category: "dinner-buffet",
    categoryLabel: "Dinner Buffet",
    caption: "Celebratory feast and festive atmosphere",
  },
  {
    id: "dinner-buffet-08",
    src: "/images/events/dinner-buffet/studio-click-house-dinner-buffet-08.jpg",
    alt: "Studio Click House team members gathered for commemorative photo",
    category: "dinner-buffet",
    categoryLabel: "Dinner Buffet",
    caption: "Celebrating another year of excellence",
  },
  {
    id: "dinner-buffet-09",
    src: "/images/events/dinner-buffet/studio-click-house-dinner-buffet-09.jpg",
    alt: "Studio Click House collective portrait at annual dinner celebration",
    category: "dinner-buffet",
    categoryLabel: "Dinner Buffet",
    caption: "The dedicated faces behind Studio Click House",
  },

  // --- Fun Day (9 Photos) ---
  {
    id: "fun-day-01",
    src: "/images/events/fun-day/studio-click-house-fun-day-01.jpg",
    alt: "Studio Click House team outdoor fun day games and team activities",
    category: "fun-day",
    categoryLabel: "Fun Day",
    caption: "Kicking off the outdoor games and sports",
  },
  {
    id: "fun-day-02",
    src: "/images/events/fun-day/studio-click-house-fun-day-02.jpg",
    alt: "Studio Click House colleagues competing in outdoor team sports",
    category: "fun-day",
    categoryLabel: "Fun Day",
    caption: "Friendly rivalry and team energy",
  },
  {
    id: "fun-day-03",
    src: "/images/events/fun-day/studio-click-house-fun-day-03.jpg",
    alt: "Studio Click House team cheering from the sidelines during fun day match",
    category: "fun-day",
    categoryLabel: "Fun Day",
    caption: "Loud cheers and enthusiastic support",
  },
  {
    id: "fun-day-04",
    src: "/images/events/fun-day/studio-click-house-fun-day-04.jpg",
    alt: "Studio Click House members taking a break under open sky at fun day",
    category: "fun-day",
    categoryLabel: "Fun Day",
    caption: "Mid-game breaks under open skies",
  },
  {
    id: "fun-day-05",
    src: "/images/events/fun-day/studio-click-house-fun-day-05.jpg",
    alt: "Studio Click House team members celebrating game victory together",
    category: "fun-day",
    categoryLabel: "Fun Day",
    caption: "High spirits and shared victories",
  },
  {
    id: "fun-day-06",
    src: "/images/events/fun-day/studio-click-house-fun-day-06.jpg",
    alt: "Studio Click House colleagues enjoying outdoor group activity",
    category: "fun-day",
    categoryLabel: "Fun Day",
    caption: "Unwinding outdoors beyond the workstations",
  },
  {
    id: "fun-day-07",
    src: "/images/events/fun-day/studio-click-house-fun-day-07.jpg",
    alt: "Studio Click House team members sharing laughs during fun day games",
    category: "fun-day",
    categoryLabel: "Fun Day",
    caption: "Energy, team spirit, and unforgettable smiles",
  },
  {
    id: "fun-day-08",
    src: "/images/events/fun-day/studio-click-house-fun-day-08.jpg",
    alt: "Studio Click House team posing outdoors with smiles and excitement",
    category: "fun-day",
    categoryLabel: "Fun Day",
    caption: "United by creativity, strengthened by play",
  },
  {
    id: "fun-day-09",
    src: "/images/events/fun-day/studio-click-house-fun-day-09.jpg",
    alt: "Studio Click House team celebrating successful fun day outing",
    category: "fun-day",
    categoryLabel: "Fun Day",
    caption: "Wrapping up a high-energy fun day together",
  },
];

export const pastEvents: CompanyEvent[] = [
  {
    id: "nepal-team-tour",
    title: "Nepal Mountain Expedition",
    summary:
      "A high-altitude studio voyage across Kathmandu and Himalayan valleys. Stepping away from retouching tablets to explore ancient stone temples, suspension bridges, and misty ridges as a collective.",
    date: "June 2026",
    location: "Nepal · Himalayas",
    status: "past",
    format: "International Tour",
    image: "/images/events/nepal-tour/studio-click-house-nepal-tour-08.webp",
    imageAlt: "Studio Click House team holding official tour banner at Nepal suspension bridge",
    focus: ["High-Altitude Trails", "Himalayan Ridge", "18 Curated Photos"],
  },
  {
    id: "mawa-evening-tour",
    title: "Mawa River Sunset Tour",
    summary:
      "An atmospheric evening road-trip out to the Padma riverbanks. Fresh river breeze, sunset silhouettes against the expressway bridge, and the traditional Ilish fish feast together under the twilight lights.",
    date: "May 2026",
    location: "Padma River · Mawa",
    status: "past",
    format: "Riverside Retreat",
    image: "/images/events/mawa-evening/studio-click-house-mawa-evening-01.jpg",
    imageAlt: "Studio Click House team gathered at Mawa Padma River at sunset",
    focus: ["Padma Bridge", "Sunset Cruise", "10 River Snapshots"],
  },
  {
    id: "studio-football-championship",
    title: "Annual Football Tournament",
    summary:
      "Under the stadium floodlights, all studio departments laced up their boots for our annual championship. Fierce competition, tactical counter-attacks, and a high-spirited full-team celebration.",
    date: "April 2026",
    location: "Dhaka Turf Arena",
    status: "past",
    format: "Championship League",
    image: "/images/events/football-match/studio-click-house-football-match-01.jpg",
    imageAlt: "Studio Click House football teams posing under floodlights",
    focus: ["Night Floodlights", "Medal Ceremony", "16 Action Photos"],
  },
  {
    id: "coxs-bazar-team-trip",
    title: "Cox's Bazar Coastal Retreat",
    summary:
      "A long-awaited getaway along the world's longest natural sea beach. Barefoot walks at golden hour, Atlantic-style waves of the Bay of Bengal, and uninterrupted downtime away from client deadlines.",
    date: "March 2026",
    location: "Bay of Bengal · Cox's Bazar",
    status: "past",
    format: "Coastal Tour",
    image: "/images/events/coxs-bazar/studio-click-house-coxs-bazar-01.jpg",
    imageAlt: "Studio Click House team enjoying sunset along Cox's Bazar beach",
    focus: ["Longest Sea Beach", "Golden Hour", "6 Beach Snapshots"],
  },
  {
    id: "annual-dinner-buffet",
    title: "Annual Gala & Grand Buffet",
    summary:
      "Dressed in formal attire for our flagship evening celebration. Recognizing artisan craftsmanship, honoring milestone deliveries, and sharing a gourmet banquet with our 100+ creative personnel.",
    date: "January 2026",
    location: "Grand Ballroom · Dhaka",
    status: "past",
    format: "Annual Gala",
    image: "/images/events/dinner-buffet/studio-click-house-dinner-buffet-01.jpg",
    imageAlt: "Studio Click House annual dinner buffet celebration gathering",
    focus: ["Craft Recognition", "Banquet Dinner", "9 Gala Photos"],
  },
  {
    id: "annual-fun-day",
    title: "Annual Outdoor Fun Day",
    summary:
      "A wide-open countryside festival filled with obstacle relays, team sack races, cricket shootouts, and unrestricted laughter under the clear afternoon sun.",
    date: "November 2025",
    location: "Resort Grounds · Gazipur",
    status: "past",
    format: "Festival & Games",
    image: "/images/events/fun-day/studio-click-house-fun-day-01.jpg",
    imageAlt: "Studio Click House team members taking part in outdoor fun day festivities",
    focus: ["Outdoor Games", "Relay Races", "9 Fun Snapshots"],
  },
];

export const eventActivities: EventActivity[] = [
  {
    id: "employee-football",
    title: "Football & Athletic League",
    description:
      "Regular evening matches give our retouchers and 3D artists space to move, sprint, and reset physically beyond pixel production.",
    image: "/images/events/football-match/studio-click-house-football-match-02.jpg",
    imageAlt: "Studio Click House employees playing football together outdoors",
  },
  {
    id: "nepal-team-tour",
    title: "Expedition Travel Tours",
    description:
      "Shared international tours built around new landscapes, mountain horizons, and shared cultural discovery as a unified studio.",
    image: "/images/events/nepal-tour/studio-click-house-nepal-tour-06.webp",
    imageAlt: "Studio Click House creative team during Nepal tour expedition",
  },
  {
    id: "mawa-sunset-tour",
    title: "Riverside Evening Escapes",
    description:
      "Quick evening road-trips to the mighty Padma river for sunset dining, fresh air, and candid bonding after major project deliveries.",
    image: "/images/events/mawa-evening/studio-click-house-mawa-evening-02.jpg",
    imageAlt: "Studio Click House team enjoying riverside breeze at Mawa",
  },
];

// Enrich past events with their full gallery photos
for (const ev of pastEvents) {
  if (ev.id === "nepal-team-tour") {
    ev.gallery = eventGalleryPhotos.filter((p) => p.category === "nepal-tour");
  } else if (ev.id === "mawa-evening-tour") {
    ev.gallery = eventGalleryPhotos.filter((p) => p.category === "mawa-evening");
  } else if (ev.id === "studio-football-championship") {
    ev.gallery = eventGalleryPhotos.filter((p) => p.category === "football-match");
  } else if (ev.id === "coxs-bazar-team-trip") {
    ev.gallery = eventGalleryPhotos.filter((p) => p.category === "coxs-bazar");
  } else if (ev.id === "annual-dinner-buffet") {
    ev.gallery = eventGalleryPhotos.filter((p) => p.category === "dinner-buffet");
  } else if (ev.id === "annual-fun-day") {
    ev.gallery = eventGalleryPhotos.filter((p) => p.category === "fun-day");
  }
}
