export const siteConfig = {
  name: "Studio Click House",
  shortName: "SCHL",
  url: "https://studioclickhouse.com",
  description:
    "Studio Click House provides image editing, retouching, and visual production for brands, studios, and production teams.",
  ogImage: "/images/brand/schl-logo.png",
  links: {
    instagram: "",
    linkedin: "",
    facebook: "",
  },
  contact: {
    email: "info@studioclickhouse.com",
    phone: "+8809609-777111",
    phoneHref: "+8809609777111",
    website: "www.studioclickhouse.com",
    websiteHref: "https://studioclickhouse.com",
    skype: "studioclickhouseltd@gmail.com",
    location: "Level 1, West Boxnagar, Demra, Dhaka-1361",
    country: "Bangladesh",
    timezone: "UTC+6",
    responseTime: "Within 15 minutes",
    offices: [
      {
        id: "bangladesh",
        country: "Bangladesh",
        city: "Dhaka",
        timezone: "UTC+6",
        address:
          "Level 1, West Boxnagar, Holding: 112/11, Demra, Dhaka-1361",
        phone: "+8809609-777111",
        phoneHref: "+8809609777111",
        email: "info@studioclickhouse.com",
        website: "www.studioclickhouse.com",
        websiteHref: "https://studioclickhouse.com",
        skype: "studioclickhouseltd@gmail.com",
      },
      {
        id: "sweden",
        country: "Sweden",
        city: "Stockholm",
        timezone: "UTC+1",
        address: "Stockholm, Sweden",
        phone: "+46855924212",
        phoneHref: "+46855924212",
        email: "andy@studioclickhouse.com",
      },
      {
        id: "australia",
        country: "Australia",
        city: "Sydney",
        timezone: "UTC+10",
        address: "Sydney, Australia",
        phone: "+61483963759",
        phoneHref: "+61483963759",
        email: "andy@studioclickhouse.com",
      },
      {
        id: "uk",
        country: "United Kingdom",
        city: "London",
        timezone: "UTC+0",
        address: "London, UK",
        phone: "+443330047739",
        phoneHref: "+443330047739",
        email: "andy@studioclickhouse.com",
      },
    ],
  },
};
